<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['name' => 'Afghanistan', 'code' => 'AF', 'code_alpha3' => 'AFG', 'flag_svg' => '🇦🇫'],
            ['name' => 'Albania', 'code' => 'AL', 'code_alpha3' => 'ALB', 'flag_svg' => '🇦🇱'],
            ['name' => 'Algeria', 'code' => 'DZ', 'code_alpha3' => 'DZA', 'flag_svg' => '🇩🇿'],
            ['name' => 'Andorra', 'code' => 'AD', 'code_alpha3' => 'AND', 'flag_svg' => '🇦🇩'],
            ['name' => 'Angola', 'code' => 'AO', 'code_alpha3' => 'AGO', 'flag_svg' => '🇦🇴'],
            ['name' => 'Argentina', 'code' => 'AR', 'code_alpha3' => 'ARG', 'flag_svg' => '🇦🇷'],
            ['name' => 'Armenia', 'code' => 'AM', 'code_alpha3' => 'ARM', 'flag_svg' => '🇦🇲'],
            ['name' => 'Australia', 'code' => 'AU', 'code_alpha3' => 'AUS', 'flag_svg' => '🇦🇺'],
            ['name' => 'Austria', 'code' => 'AT', 'code_alpha3' => 'AUT', 'flag_svg' => '🇦🇹'],
            ['name' => 'Azerbaijan', 'code' => 'AZ', 'code_alpha3' => 'AZE', 'flag_svg' => '🇦🇿'],
            ['name' => 'Bahamas', 'code' => 'BS', 'code_alpha3' => 'BHS', 'flag_svg' => '🇧🇸'],
            ['name' => 'Bahrain', 'code' => 'BH', 'code_alpha3' => 'BHR', 'flag_svg' => '🇧🇭'],
            ['name' => 'Bangladesh', 'code' => 'BD', 'code_alpha3' => 'BGD', 'flag_svg' => '🇧🇩'],
            ['name' => 'Barbados', 'code' => 'BB', 'code_alpha3' => 'BRB', 'flag_svg' => '🇧🇧'],
            ['name' => 'Belarus', 'code' => 'BY', 'code_alpha3' => 'BLR', 'flag_svg' => '🇧🇾'],
            ['name' => 'Belgium', 'code' => 'BE', 'code_alpha3' => 'BEL', 'flag_svg' => '🇧🇪'],
            ['name' => 'Belize', 'code' => 'BZ', 'code_alpha3' => 'BLZ', 'flag_svg' => '🇧🇿'],
            ['name' => 'Benin', 'code' => 'BJ', 'code_alpha3' => 'BEN', 'flag_svg' => '🇧🇯'],
            ['name' => 'Bhutan', 'code' => 'BT', 'code_alpha3' => 'BTN', 'flag_svg' => '🇧🇹'],
            ['name' => 'Bolivia', 'code' => 'BO', 'code_alpha3' => 'BOL', 'flag_svg' => '🇧🇴'],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BA', 'code_alpha3' => 'BIH', 'flag_svg' => '🇧🇦'],
            ['name' => 'Botswana', 'code' => 'BW', 'code_alpha3' => 'BWA', 'flag_svg' => '🇧🇼'],
            ['name' => 'Brazil', 'code' => 'BR', 'code_alpha3' => 'BRA', 'flag_svg' => '🇧🇷'],
            ['name' => 'Brunei', 'code' => 'BN', 'code_alpha3' => 'BRN', 'flag_svg' => '🇧🇳'],
            ['name' => 'Bulgaria', 'code' => 'BG', 'code_alpha3' => 'BGR', 'flag_svg' => '🇧🇬'],
            ['name' => 'Burkina Faso', 'code' => 'BF', 'code_alpha3' => 'BFA', 'flag_svg' => '🇧🇫'],
            ['name' => 'Burundi', 'code' => 'BI', 'code_alpha3' => 'BDI', 'flag_svg' => '🇧🇮'],
            ['name' => 'Cambodia', 'code' => 'KH', 'code_alpha3' => 'KHM', 'flag_svg' => '🇰🇭'],
            ['name' => 'Cameroon', 'code' => 'CM', 'code_alpha3' => 'CMR', 'flag_svg' => '🇨🇲'],
            ['name' => 'Canada', 'code' => 'CA', 'code_alpha3' => 'CAN', 'flag_svg' => '🇨🇦'],
            ['name' => 'Cape Verde', 'code' => 'CV', 'code_alpha3' => 'CPV', 'flag_svg' => '🇨🇻'],
            ['name' => 'Central African Republic', 'code' => 'CF', 'code_alpha3' => 'CAF', 'flag_svg' => '🇨🇫'],
            ['name' => 'Chad', 'code' => 'TD', 'code_alpha3' => 'TCD', 'flag_svg' => '🇹🇩'],
            ['name' => 'Chile', 'code' => 'CL', 'code_alpha3' => 'CHL', 'flag_svg' => '🇨🇱'],
            ['name' => 'China', 'code' => 'CN', 'code_alpha3' => 'CHN', 'flag_svg' => '🇨🇳'],
            ['name' => 'Colombia', 'code' => 'CO', 'code_alpha3' => 'COL', 'flag_svg' => '🇨🇴'],
            ['name' => 'Comoros', 'code' => 'KM', 'code_alpha3' => 'COM', 'flag_svg' => '🇰🇲'],
            ['name' => 'Congo', 'code' => 'CG', 'code_alpha3' => 'COG', 'flag_svg' => '🇨🇬'],
            ['name' => 'Costa Rica', 'code' => 'CR', 'code_alpha3' => 'CRI', 'flag_svg' => '🇨🇷'],
            ['name' => 'Croatia', 'code' => 'HR', 'code_alpha3' => 'HRV', 'flag_svg' => '🇭🇷'],
            ['name' => 'Cuba', 'code' => 'CU', 'code_alpha3' => 'CUB', 'flag_svg' => '🇨🇺'],
            ['name' => 'Cyprus', 'code' => 'CY', 'code_alpha3' => 'CYP', 'flag_svg' => '🇨🇾'],
            ['name' => 'Czech Republic', 'code' => 'CZ', 'code_alpha3' => 'CZE', 'flag_svg' => '🇨🇿'],
            ['name' => 'Democratic Republic of the Congo', 'code' => 'CD', 'code_alpha3' => 'COD', 'flag_svg' => '🇨🇩'],
            ['name' => 'Denmark', 'code' => 'DK', 'code_alpha3' => 'DNK', 'flag_svg' => '🇩🇰'],
            ['name' => 'Djibouti', 'code' => 'DJ', 'code_alpha3' => 'DJI', 'flag_svg' => '🇩🇯'],
            ['name' => 'Dominica', 'code' => 'DM', 'code_alpha3' => 'DMA', 'flag_svg' => '🇩🇲'],
            ['name' => 'Dominican Republic', 'code' => 'DO', 'code_alpha3' => 'DOM', 'flag_svg' => '🇩🇴'],
            ['name' => 'Ecuador', 'code' => 'EC', 'code_alpha3' => 'ECU', 'flag_svg' => '🇪🇨'],
            ['name' => 'Egypt', 'code' => 'EG', 'code_alpha3' => 'EGY', 'flag_svg' => '🇪🇬'],
            ['name' => 'El Salvador', 'code' => 'SV', 'code_alpha3' => 'SLV', 'flag_svg' => '🇸🇻'],
            ['name' => 'Equatorial Guinea', 'code' => 'GQ', 'code_alpha3' => 'GNQ', 'flag_svg' => '🇬🇶'],
            ['name' => 'Eritrea', 'code' => 'ER', 'code_alpha3' => 'ERI', 'flag_svg' => '🇪🇷'],
            ['name' => 'Estonia', 'code' => 'EE', 'code_alpha3' => 'EST', 'flag_svg' => '🇪🇪'],
            ['name' => 'Eswatini', 'code' => 'SZ', 'code_alpha3' => 'SWZ', 'flag_svg' => '🇸🇿'],
            ['name' => 'Ethiopia', 'code' => 'ET', 'code_alpha3' => 'ETH', 'flag_svg' => '🇪🇹'],
            ['name' => 'Fiji', 'code' => 'FJ', 'code_alpha3' => 'FJI', 'flag_svg' => '🇫🇯'],
            ['name' => 'Finland', 'code' => 'FI', 'code_alpha3' => 'FIN', 'flag_svg' => '🇫🇮'],
            ['name' => 'France', 'code' => 'FR', 'code_alpha3' => 'FRA', 'flag_svg' => '🇫🇷'],
            ['name' => 'Gabon', 'code' => 'GA', 'code_alpha3' => 'GAB', 'flag_svg' => '🇬🇦'],
            ['name' => 'Gambia', 'code' => 'GM', 'code_alpha3' => 'GMB', 'flag_svg' => '🇬🇲'],
            ['name' => 'Georgia', 'code' => 'GE', 'code_alpha3' => 'GEO', 'flag_svg' => '🇬🇪'],
            ['name' => 'Germany', 'code' => 'DE', 'code_alpha3' => 'DEU', 'flag_svg' => '🇩🇪'],
            ['name' => 'Ghana', 'code' => 'GH', 'code_alpha3' => 'GHA', 'flag_svg' => '🇬🇭'],
            ['name' => 'Greece', 'code' => 'GR', 'code_alpha3' => 'GRC', 'flag_svg' => '🇬🇷'],
            ['name' => 'Grenada', 'code' => 'GD', 'code_alpha3' => 'GRD', 'flag_svg' => '🇬🇩'],
            ['name' => 'Guatemala', 'code' => 'GT', 'code_alpha3' => 'GTM', 'flag_svg' => '🇬🇹'],
            ['name' => 'Guinea', 'code' => 'GN', 'code_alpha3' => 'GIN', 'flag_svg' => '🇬🇳'],
            ['name' => 'Guinea-Bissau', 'code' => 'GW', 'code_alpha3' => 'GNB', 'flag_svg' => '🇬🇼'],
            ['name' => 'Guyana', 'code' => 'GY', 'code_alpha3' => 'GUY', 'flag_svg' => '🇬🇾'],
            ['name' => 'Haiti', 'code' => 'HT', 'code_alpha3' => 'HTI', 'flag_svg' => '🇭🇹'],
            ['name' => 'Honduras', 'code' => 'HN', 'code_alpha3' => 'HND', 'flag_svg' => '🇭🇳'],
            ['name' => 'Hungary', 'code' => 'HU', 'code_alpha3' => 'HUN', 'flag_svg' => '🇭🇺'],
            ['name' => 'Iceland', 'code' => 'IS', 'code_alpha3' => 'ISL', 'flag_svg' => '🇮🇸'],
            ['name' => 'India', 'code' => 'IN', 'code_alpha3' => 'IND', 'flag_svg' => '🇮🇳'],
            ['name' => 'Indonesia', 'code' => 'ID', 'code_alpha3' => 'IDN', 'flag_svg' => '🇮🇩'],
            ['name' => 'Iran', 'code' => 'IR', 'code_alpha3' => 'IRN', 'flag_svg' => '🇮🇷'],
            ['name' => 'Iraq', 'code' => 'IQ', 'code_alpha3' => 'IRQ', 'flag_svg' => '🇮🇶'],
            ['name' => 'Ireland', 'code' => 'IE', 'code_alpha3' => 'IRL', 'flag_svg' => '🇮🇪'],
            ['name' => 'Israel', 'code' => 'IL', 'code_alpha3' => 'ISR', 'flag_svg' => '🇮🇱'],
            ['name' => 'Italy', 'code' => 'IT', 'code_alpha3' => 'ITA', 'flag_svg' => '🇮🇹'],
            ['name' => 'Jamaica', 'code' => 'JM', 'code_alpha3' => 'JAM', 'flag_svg' => '🇯🇲'],
            ['name' => 'Japan', 'code' => 'JP', 'code_alpha3' => 'JPN', 'flag_svg' => '🇯🇵'],
            ['name' => 'Jordan', 'code' => 'JO', 'code_alpha3' => 'JOR', 'flag_svg' => '🇯🇴'],
            ['name' => 'Kazakhstan', 'code' => 'KZ', 'code_alpha3' => 'KAZ', 'flag_svg' => '🇰🇿'],
            ['name' => 'Kenya', 'code' => 'KE', 'code_alpha3' => 'KEN', 'flag_svg' => '🇰🇪'],
            ['name' => 'Kiribati', 'code' => 'KI', 'code_alpha3' => 'KIR', 'flag_svg' => '🇰🇮'],
            ['name' => 'Kuwait', 'code' => 'KW', 'code_alpha3' => 'KWT', 'flag_svg' => '🇰🇼'],
            ['name' => 'Kyrgyzstan', 'code' => 'KG', 'code_alpha3' => 'KGZ', 'flag_svg' => '🇰🇬'],
            ['name' => 'Laos', 'code' => 'LA', 'code_alpha3' => 'LAO', 'flag_svg' => '🇱🇦'],
            ['name' => 'Latvia', 'code' => 'LV', 'code_alpha3' => 'LVA', 'flag_svg' => '🇱🇻'],
            ['name' => 'Lebanon', 'code' => 'LB', 'code_alpha3' => 'LBN', 'flag_svg' => '🇱🇧'],
            ['name' => 'Lesotho', 'code' => 'LS', 'code_alpha3' => 'LSO', 'flag_svg' => '🇱🇸'],
            ['name' => 'Liberia', 'code' => 'LR', 'code_alpha3' => 'LBR', 'flag_svg' => '🇱🇷'],
            ['name' => 'Libya', 'code' => 'LY', 'code_alpha3' => 'LBY', 'flag_svg' => '🇱🇾'],
            ['name' => 'Liechtenstein', 'code' => 'LI', 'code_alpha3' => 'LIE', 'flag_svg' => '🇱🇮'],
            ['name' => 'Lithuania', 'code' => 'LT', 'code_alpha3' => 'LTU', 'flag_svg' => '🇱🇹'],
            ['name' => 'Luxembourg', 'code' => 'LU', 'code_alpha3' => 'LUX', 'flag_svg' => '🇱🇺'],
            ['name' => 'Madagascar', 'code' => 'MG', 'code_alpha3' => 'MDG', 'flag_svg' => '🇲🇬'],
            ['name' => 'Malawi', 'code' => 'MW', 'code_alpha3' => 'MWI', 'flag_svg' => '🇲🇼'],
            ['name' => 'Malaysia', 'code' => 'MY', 'code_alpha3' => 'MYS', 'flag_svg' => '🇲🇾'],
            ['name' => 'Maldives', 'code' => 'MV', 'code_alpha3' => 'MDV', 'flag_svg' => '🇲🇻'],
            ['name' => 'Mali', 'code' => 'ML', 'code_alpha3' => 'MLI', 'flag_svg' => '🇲🇱'],
            ['name' => 'Malta', 'code' => 'MT', 'code_alpha3' => 'MLT', 'flag_svg' => '🇲🇹'],
            ['name' => 'Marshall Islands', 'code' => 'MH', 'code_alpha3' => 'MHL', 'flag_svg' => '🇲🇭'],
            ['name' => 'Mauritania', 'code' => 'MR', 'code_alpha3' => 'MRT', 'flag_svg' => '🇲🇷'],
            ['name' => 'Mauritius', 'code' => 'MU', 'code_alpha3' => 'MUS', 'flag_svg' => '🇲🇺'],
            ['name' => 'Mexico', 'code' => 'MX', 'code_alpha3' => 'MEX', 'flag_svg' => '🇲🇽'],
            ['name' => 'Micronesia', 'code' => 'FM', 'code_alpha3' => 'FSM', 'flag_svg' => '🇫🇲'],
            ['name' => 'Moldova', 'code' => 'MD', 'code_alpha3' => 'MDA', 'flag_svg' => '🇲🇩'],
            ['name' => 'Monaco', 'code' => 'MC', 'code_alpha3' => 'MCO', 'flag_svg' => '🇲🇨'],
            ['name' => 'Mongolia', 'code' => 'MN', 'code_alpha3' => 'MNG', 'flag_svg' => '🇲🇳'],
            ['name' => 'Montenegro', 'code' => 'ME', 'code_alpha3' => 'MNE', 'flag_svg' => '🇲🇪'],
            ['name' => 'Morocco', 'code' => 'MA', 'code_alpha3' => 'MAR', 'flag_svg' => '🇲🇦'],
            ['name' => 'Mozambique', 'code' => 'MZ', 'code_alpha3' => 'MOZ', 'flag_svg' => '🇲🇿'],
            ['name' => 'Myanmar', 'code' => 'MM', 'code_alpha3' => 'MMR', 'flag_svg' => '🇲🇲'],
            ['name' => 'Namibia', 'code' => 'NA', 'code_alpha3' => 'NAM', 'flag_svg' => '🇳🇦'],
            ['name' => 'Nauru', 'code' => 'NR', 'code_alpha3' => 'NRU', 'flag_svg' => '🇳🇷'],
            ['name' => 'Nepal', 'code' => 'NP', 'code_alpha3' => 'NPL', 'flag_svg' => '🇳🇵'],
            ['name' => 'Netherlands', 'code' => 'NL', 'code_alpha3' => 'NLD', 'flag_svg' => '🇳🇱'],
            ['name' => 'New Zealand', 'code' => 'NZ', 'code_alpha3' => 'NZL', 'flag_svg' => '🇳🇿'],
            ['name' => 'Nicaragua', 'code' => 'NI', 'code_alpha3' => 'NIC', 'flag_svg' => '🇳🇮'],
            ['name' => 'Niger', 'code' => 'NE', 'code_alpha3' => 'NER', 'flag_svg' => '🇳🇪'],
            ['name' => 'Nigeria', 'code' => 'NG', 'code_alpha3' => 'NGA', 'flag_svg' => '🇳🇬'],
            ['name' => 'North Korea', 'code' => 'KP', 'code_alpha3' => 'PRK', 'flag_svg' => '🇰🇵'],
            ['name' => 'North Macedonia', 'code' => 'MK', 'code_alpha3' => 'MKD', 'flag_svg' => '🇲🇰'],
            ['name' => 'Norway', 'code' => 'NO', 'code_alpha3' => 'NOR', 'flag_svg' => '🇳🇴'],
            ['name' => 'Oman', 'code' => 'OM', 'code_alpha3' => 'OMN', 'flag_svg' => '🇴🇲'],
            ['name' => 'Pakistan', 'code' => 'PK', 'code_alpha3' => 'PAK', 'flag_svg' => '🇵🇰'],
            ['name' => 'Palau', 'code' => 'PW', 'code_alpha3' => 'PLW', 'flag_svg' => '🇵🇼'],
            ['name' => 'Panama', 'code' => 'PA', 'code_alpha3' => 'PAN', 'flag_svg' => '🇵🇦'],
            ['name' => 'Papua New Guinea', 'code' => 'PG', 'code_alpha3' => 'PNG', 'flag_svg' => '🇵🇬'],
            ['name' => 'Paraguay', 'code' => 'PY', 'code_alpha3' => 'PRY', 'flag_svg' => '🇵🇾'],
            ['name' => 'Peru', 'code' => 'PE', 'code_alpha3' => 'PER', 'flag_svg' => '🇵🇪'],
            ['name' => 'Philippines', 'code' => 'PH', 'code_alpha3' => 'PHL', 'flag_svg' => '🇵🇭'],
            ['name' => 'Poland', 'code' => 'PL', 'code_alpha3' => 'POL', 'flag_svg' => '🇵🇱'],
            ['name' => 'Portugal', 'code' => 'PT', 'code_alpha3' => 'PRT', 'flag_svg' => '🇵🇹'],
            ['name' => 'Qatar', 'code' => 'QA', 'code_alpha3' => 'QAT', 'flag_svg' => '🇶🇦'],
            ['name' => 'Romania', 'code' => 'RO', 'code_alpha3' => 'ROU', 'flag_svg' => '🇷🇴'],
            ['name' => 'Russia', 'code' => 'RU', 'code_alpha3' => 'RUS', 'flag_svg' => '🇷🇺'],
            ['name' => 'Rwanda', 'code' => 'RW', 'code_alpha3' => 'RWA', 'flag_svg' => '🇷🇼'],
            ['name' => 'Saint Kitts and Nevis', 'code' => 'KN', 'code_alpha3' => 'KNA', 'flag_svg' => '🇰🇳'],
            ['name' => 'Saint Lucia', 'code' => 'LC', 'code_alpha3' => 'LCA', 'flag_svg' => '🇱🇨'],
            ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VC', 'code_alpha3' => 'VCT', 'flag_svg' => '🇻🇨'],
            ['name' => 'Samoa', 'code' => 'WS', 'code_alpha3' => 'WSM', 'flag_svg' => '🇼🇸'],
            ['name' => 'San Marino', 'code' => 'SM', 'code_alpha3' => 'SMR', 'flag_svg' => '🇸🇲'],
            ['name' => 'Saudi Arabia', 'code' => 'SA', 'code_alpha3' => 'SAU', 'flag_svg' => '🇸🇦'],
            ['name' => 'Senegal', 'code' => 'SN', 'code_alpha3' => 'SEN', 'flag_svg' => '🇸🇳'],
            ['name' => 'Serbia', 'code' => 'RS', 'code_alpha3' => 'SRB', 'flag_svg' => '🇷🇸'],
            ['name' => 'Seychelles', 'code' => 'SC', 'code_alpha3' => 'SYC', 'flag_svg' => '🇸🇨'],
            ['name' => 'Sierra Leone', 'code' => 'SL', 'code_alpha3' => 'SLE', 'flag_svg' => '🇸🇱'],
            ['name' => 'Singapore', 'code' => 'SG', 'code_alpha3' => 'SGP', 'flag_svg' => '🇸🇬'],
            ['name' => 'Slovakia', 'code' => 'SK', 'code_alpha3' => 'SVK', 'flag_svg' => '🇸🇰'],
            ['name' => 'Slovenia', 'code' => 'SI', 'code_alpha3' => 'SVN', 'flag_svg' => '🇸🇮'],
            ['name' => 'Solomon Islands', 'code' => 'SB', 'code_alpha3' => 'SLB', 'flag_svg' => '🇸🇧'],
            ['name' => 'Somalia', 'code' => 'SO', 'code_alpha3' => 'SOM', 'flag_svg' => '🇸🇴'],
            ['name' => 'South Africa', 'code' => 'ZA', 'code_alpha3' => 'ZAF', 'flag_svg' => '🇿🇦'],
            ['name' => 'South Korea', 'code' => 'KR', 'code_alpha3' => 'KOR', 'flag_svg' => '🇰🇷'],
            ['name' => 'South Sudan', 'code' => 'SS', 'code_alpha3' => 'SSD', 'flag_svg' => '🇸🇸'],
            ['name' => 'Spain', 'code' => 'ES', 'code_alpha3' => 'ESP', 'flag_svg' => '🇪🇸'],
            ['name' => 'Sri Lanka', 'code' => 'LK', 'code_alpha3' => 'LKA', 'flag_svg' => '🇱🇰'],
            ['name' => 'Sudan', 'code' => 'SD', 'code_alpha3' => 'SDN', 'flag_svg' => '🇸🇩'],
            ['name' => 'Suriname', 'code' => 'SR', 'code_alpha3' => 'SUR', 'flag_svg' => '🇸🇷'],
            ['name' => 'Sweden', 'code' => 'SE', 'code_alpha3' => 'SWE', 'flag_svg' => '🇸🇪'],
            ['name' => 'Switzerland', 'code' => 'CH', 'code_alpha3' => 'CHE', 'flag_svg' => '🇨🇭'],
            ['name' => 'Syria', 'code' => 'SY', 'code_alpha3' => 'SYR', 'flag_svg' => '🇸🇾'],
            ['name' => 'Taiwan', 'code' => 'TW', 'code_alpha3' => 'TWN', 'flag_svg' => '🇹🇼'],
            ['name' => 'Tajikistan', 'code' => 'TJ', 'code_alpha3' => 'TJK', 'flag_svg' => '🇹🇯'],
            ['name' => 'Tanzania', 'code' => 'TZ', 'code_alpha3' => 'TZA', 'flag_svg' => '🇹🇿'],
            ['name' => 'Thailand', 'code' => 'TH', 'code_alpha3' => 'THA', 'flag_svg' => '🇹🇭'],
            ['name' => 'Timor-Leste', 'code' => 'TL', 'code_alpha3' => 'TLS', 'flag_svg' => '🇹🇱'],
            ['name' => 'Togo', 'code' => 'TG', 'code_alpha3' => 'TGO', 'flag_svg' => '🇹🇬'],
            ['name' => 'Tonga', 'code' => 'TO', 'code_alpha3' => 'TON', 'flag_svg' => '🇹🇴'],
            ['name' => 'Trinidad and Tobago', 'code' => 'TT', 'code_alpha3' => 'TTO', 'flag_svg' => '🇹🇹'],
            ['name' => 'Tunisia', 'code' => 'TN', 'code_alpha3' => 'TUN', 'flag_svg' => '🇹🇳'],
            ['name' => 'Turkey', 'code' => 'TR', 'code_alpha3' => 'TUR', 'flag_svg' => '🇹🇷'],
            ['name' => 'Turkmenistan', 'code' => 'TM', 'code_alpha3' => 'TKM', 'flag_svg' => '🇹🇲'],
            ['name' => 'Tuvalu', 'code' => 'TV', 'code_alpha3' => 'TUV', 'flag_svg' => '🇹🇻'],
            ['name' => 'Uganda', 'code' => 'UG', 'code_alpha3' => 'UGA', 'flag_svg' => '🇺🇬'],
            ['name' => 'Ukraine', 'code' => 'UA', 'code_alpha3' => 'UKR', 'flag_svg' => '🇺🇦'],
            ['name' => 'United Arab Emirates', 'code' => 'AE', 'code_alpha3' => 'ARE', 'flag_svg' => '🇦🇪'],
            ['name' => 'United Kingdom', 'code' => 'GB', 'code_alpha3' => 'GBR', 'flag_svg' => '🇬🇧'],
            ['name' => 'United States', 'code' => 'US', 'code_alpha3' => 'USA', 'flag_svg' => '🇺🇸'],
            ['name' => 'Uruguay', 'code' => 'UY', 'code_alpha3' => 'URY', 'flag_svg' => '🇺🇾'],
            ['name' => 'Uzbekistan', 'code' => 'UZ', 'code_alpha3' => 'UZB', 'flag_svg' => '🇺🇿'],
            ['name' => 'Vanuatu', 'code' => 'VU', 'code_alpha3' => 'VUT', 'flag_svg' => '🇻🇺'],
            ['name' => 'Vatican City', 'code' => 'VA', 'code_alpha3' => 'VAT', 'flag_svg' => '🇻🇦'],
            ['name' => 'Venezuela', 'code' => 'VE', 'code_alpha3' => 'VEN', 'flag_svg' => '🇻🇪'],
            ['name' => 'Vietnam', 'code' => 'VN', 'code_alpha3' => 'VNM', 'flag_svg' => '🇻🇳'],
            ['name' => 'Yemen', 'code' => 'YE', 'code_alpha3' => 'YEM', 'flag_svg' => '🇾🇪'],
            ['name' => 'Zambia', 'code' => 'ZM', 'code_alpha3' => 'ZMB', 'flag_svg' => '🇿🇲'],
            ['name' => 'Zimbabwe', 'code' => 'ZW', 'code_alpha3' => 'ZWE', 'flag_svg' => '🇿🇼'],
        ];

        foreach ($countries as $country) {
            Country::create($country);
        }
    }
}
