<?php

namespace Database\Seeders;

use App\Models\Currency;
use Illuminate\Database\Seeder;

class CurrencySeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->currencies() as $data) {
            Currency::updateOrCreate(
                ['code' => $data['code']],
                $data
            );
        }

        $this->command->info('Currencies seeded: ' . count($this->currencies()) . ' worldwide.');
    }

    private function currencies(): array
    {
        return [
            ['code' => 'USD', 'name' => 'US Dollar', 'symbol' => '$', 'precision' => 2],
            ['code' => 'EUR', 'name' => 'Euro', 'symbol' => '€', 'precision' => 2],
            ['code' => 'GBP', 'name' => 'British Pound', 'symbol' => '£', 'precision' => 2],
            ['code' => 'JPY', 'name' => 'Japanese Yen', 'symbol' => '¥', 'precision' => 0],
            ['code' => 'CNY', 'name' => 'Chinese Yuan', 'symbol' => '¥', 'precision' => 2],
            ['code' => 'INR', 'name' => 'Indian Rupee', 'symbol' => '₹', 'precision' => 2],
            ['code' => 'AUD', 'name' => 'Australian Dollar', 'symbol' => 'A$', 'precision' => 2],
            ['code' => 'CAD', 'name' => 'Canadian Dollar', 'symbol' => 'C$', 'precision' => 2],
            ['code' => 'CHF', 'name' => 'Swiss Franc', 'symbol' => 'CHF', 'precision' => 2],
            ['code' => 'HKD', 'name' => 'Hong Kong Dollar', 'symbol' => 'HK$', 'precision' => 2],
            ['code' => 'SGD', 'name' => 'Singapore Dollar', 'symbol' => 'S$', 'precision' => 2],
            ['code' => 'SEK', 'name' => 'Swedish Krona', 'symbol' => 'kr', 'precision' => 2],
            ['code' => 'KRW', 'name' => 'South Korean Won', 'symbol' => '₩', 'precision' => 0],
            ['code' => 'NOK', 'name' => 'Norwegian Krone', 'symbol' => 'kr', 'precision' => 2],
            ['code' => 'NZD', 'name' => 'New Zealand Dollar', 'symbol' => 'NZ$', 'precision' => 2],
            ['code' => 'MXN', 'name' => 'Mexican Peso', 'symbol' => 'Mex$', 'precision' => 2],
            ['code' => 'BRL', 'name' => 'Brazilian Real', 'symbol' => 'R$', 'precision' => 2],
            ['code' => 'RUB', 'name' => 'Russian Ruble', 'symbol' => '₽', 'precision' => 2],
            ['code' => 'ZAR', 'name' => 'South African Rand', 'symbol' => 'R', 'precision' => 2],
            ['code' => 'TRY', 'name' => 'Turkish Lira', 'symbol' => '₺', 'precision' => 2],
            ['code' => 'SAR', 'name' => 'Saudi Riyal', 'symbol' => '﷼', 'precision' => 2],
            ['code' => 'AED', 'name' => 'UAE Dirham', 'symbol' => 'د.إ', 'precision' => 2],
            ['code' => 'PKR', 'name' => 'Pakistani Rupee', 'symbol' => '₨', 'precision' => 2],
            ['code' => 'BDT', 'name' => 'Bangladeshi Taka', 'symbol' => '৳', 'precision' => 2],
            ['code' => 'IDR', 'name' => 'Indonesian Rupiah', 'symbol' => 'Rp', 'precision' => 0],
            ['code' => 'MYR', 'name' => 'Malaysian Ringgit', 'symbol' => 'RM', 'precision' => 2],
            ['code' => 'PHP', 'name' => 'Philippine Peso', 'symbol' => '₱', 'precision' => 2],
            ['code' => 'THB', 'name' => 'Thai Baht', 'symbol' => '฿', 'precision' => 2],
            ['code' => 'VND', 'name' => 'Vietnamese Dong', 'symbol' => '₫', 'precision' => 0],
            ['code' => 'TWD', 'name' => 'Taiwan Dollar', 'symbol' => 'NT$', 'precision' => 2],
            ['code' => 'PLN', 'name' => 'Polish Zloty', 'symbol' => 'zł', 'precision' => 2],
            ['code' => 'CZK', 'name' => 'Czech Koruna', 'symbol' => 'Kč', 'precision' => 2],
            ['code' => 'HUF', 'name' => 'Hungarian Forint', 'symbol' => 'Ft', 'precision' => 2],
            ['code' => 'RON', 'name' => 'Romanian Leu', 'symbol' => 'lei', 'precision' => 2],
            ['code' => 'DKK', 'name' => 'Danish Krone', 'symbol' => 'kr', 'precision' => 2],
            ['code' => 'ISK', 'name' => 'Icelandic Krona', 'symbol' => 'kr', 'precision' => 2],
            ['code' => 'CLP', 'name' => 'Chilean Peso', 'symbol' => 'CLP$', 'precision' => 0],
            ['code' => 'COP', 'name' => 'Colombian Peso', 'symbol' => 'COL$', 'precision' => 0],
            ['code' => 'ARS', 'name' => 'Argentine Peso', 'symbol' => 'AR$', 'precision' => 2],
            ['code' => 'PEN', 'name' => 'Peruvian Sol', 'symbol' => 'S/', 'precision' => 2],
            ['code' => 'EGP', 'name' => 'Egyptian Pound', 'symbol' => 'E£', 'precision' => 2],
            ['code' => 'NGN', 'name' => 'Nigerian Naira', 'symbol' => '₦', 'precision' => 2],
            ['code' => 'KES', 'name' => 'Kenyan Shilling', 'symbol' => 'KSh', 'precision' => 2],
            ['code' => 'GHS', 'name' => 'Ghanaian Cedi', 'symbol' => 'GH₵', 'precision' => 2],
            ['code' => 'MAD', 'name' => 'Moroccan Dirham', 'symbol' => 'DH', 'precision' => 2],
            ['code' => 'DZD', 'name' => 'Algerian Dinar', 'symbol' => 'DA', 'precision' => 2],
            ['code' => 'TND', 'name' => 'Tunisian Dinar', 'symbol' => 'DT', 'precision' => 3],
            ['code' => 'QAR', 'name' => 'Qatari Riyal', 'symbol' => 'QR', 'precision' => 2],
            ['code' => 'KWD', 'name' => 'Kuwaiti Dinar', 'symbol' => 'KD', 'precision' => 3],
            ['code' => 'BHD', 'name' => 'Bahraini Dinar', 'symbol' => 'BD', 'precision' => 3],
            ['code' => 'OMR', 'name' => 'Omani Rial', 'symbol' => 'RO', 'precision' => 3],
            ['code' => 'JOD', 'name' => 'Jordanian Dinar', 'symbol' => 'JD', 'precision' => 3],
            ['code' => 'ILS', 'name' => 'Israeli Shekel', 'symbol' => '₪', 'precision' => 2],
            ['code' => 'LKR', 'name' => 'Sri Lankan Rupee', 'symbol' => 'Rs', 'precision' => 2],
            ['code' => 'NPR', 'name' => 'Nepalese Rupee', 'symbol' => 'Rs', 'precision' => 2],
            ['code' => 'MMK', 'name' => 'Myanmar Kyat', 'symbol' => 'K', 'precision' => 2],
            ['code' => 'KHR', 'name' => 'Cambodian Riel', 'symbol' => '៛', 'precision' => 2],
            ['code' => 'LAK', 'name' => 'Lao Kip', 'symbol' => '₭', 'precision' => 2],
            ['code' => 'MNT', 'name' => 'Mongolian Tugrik', 'symbol' => '₮', 'precision' => 2],
            ['code' => 'KZT', 'name' => 'Kazakhstani Tenge', 'symbol' => '₸', 'precision' => 2],
            ['code' => 'UZS', 'name' => 'Uzbekistani Som', 'symbol' => 'so\'m', 'precision' => 2],
            ['code' => 'AZN', 'name' => 'Azerbaijani Manat', 'symbol' => '₼', 'precision' => 2],
            ['code' => 'GEL', 'name' => 'Georgian Lari', 'symbol' => '₾', 'precision' => 2],
            ['code' => 'AMD', 'name' => 'Armenian Dram', 'symbol' => '֏', 'precision' => 2],
            ['code' => 'UAH', 'name' => 'Ukrainian Hryvnia', 'symbol' => '₴', 'precision' => 2],
            ['code' => 'BYN', 'name' => 'Belarusian Ruble', 'symbol' => 'Br', 'precision' => 2],
            ['code' => 'RSD', 'name' => 'Serbian Dinar', 'symbol' => 'din', 'precision' => 2],
            ['code' => 'HRK', 'name' => 'Croatian Kuna', 'symbol' => 'kn', 'precision' => 2],
            ['code' => 'BGN', 'name' => 'Bulgarian Lev', 'symbol' => 'лв', 'precision' => 2],
            ['code' => 'ALL', 'name' => 'Albanian Lek', 'symbol' => 'L', 'precision' => 2],
            ['code' => 'MKD', 'name' => 'Macedonian Denar', 'symbol' => 'ден', 'precision' => 2],
            ['code' => 'BAM', 'name' => 'Bosnia Convertible Mark', 'symbol' => 'KM', 'precision' => 2],
            ['code' => 'MDL', 'name' => 'Moldovan Leu', 'symbol' => 'L', 'precision' => 2],
            ['code' => 'UYU', 'name' => 'Uruguayan Peso', 'symbol' => '$U', 'precision' => 2],
            ['code' => 'PYG', 'name' => 'Paraguayan Guarani', 'symbol' => '₲', 'precision' => 0],
            ['code' => 'BOB', 'name' => 'Bolivian Boliviano', 'symbol' => 'Bs', 'precision' => 2],
            ['code' => 'VES', 'name' => 'Venezuelan Bolivar', 'symbol' => 'Bs', 'precision' => 2],
            ['code' => 'CRC', 'name' => 'Costa Rican Colon', 'symbol' => '₡', 'precision' => 2],
            ['code' => 'DOP', 'name' => 'Dominican Peso', 'symbol' => 'RD$', 'precision' => 2],
            ['code' => 'GTQ', 'name' => 'Guatemalan Quetzal', 'symbol' => 'Q', 'precision' => 2],
            ['code' => 'HNL', 'name' => 'Honduran Lempira', 'symbol' => 'L', 'precision' => 2],
            ['code' => 'NIO', 'name' => 'Nicaraguan Cordoba', 'symbol' => 'C$', 'precision' => 2],
            ['code' => 'PAB', 'name' => 'Panamanian Balboa', 'symbol' => 'B/.', 'precision' => 2],
            ['code' => 'JMD', 'name' => 'Jamaican Dollar', 'symbol' => 'J$', 'precision' => 2],
            ['code' => 'TTD', 'name' => 'Trinidad & Tobago Dollar', 'symbol' => 'TT$', 'precision' => 2],
            ['code' => 'BBD', 'name' => 'Barbadian Dollar', 'symbol' => 'Bds$', 'precision' => 2],
            ['code' => 'BSD', 'name' => 'Bahamian Dollar', 'symbol' => 'B$', 'precision' => 2],
            ['code' => 'BMD', 'name' => 'Bermudian Dollar', 'symbol' => 'BD$', 'precision' => 2],
            ['code' => 'KYD', 'name' => 'Cayman Islands Dollar', 'symbol' => 'CI$', 'precision' => 2],
            ['code' => 'XCD', 'name' => 'East Caribbean Dollar', 'symbol' => 'EC$', 'precision' => 2],
            ['code' => 'AWG', 'name' => 'Aruban Florin', 'symbol' => 'Afl', 'precision' => 2],
            ['code' => 'ANG', 'name' => 'Netherlands Antillean Guilder', 'symbol' => 'NAƒ', 'precision' => 2],
            ['code' => 'FJD', 'name' => 'Fijian Dollar', 'symbol' => 'FJ$', 'precision' => 2],
            ['code' => 'PGK', 'name' => 'Papua New Guinean Kina', 'symbol' => 'K', 'precision' => 2],
            ['code' => 'SBD', 'name' => 'Solomon Islands Dollar', 'symbol' => 'SI$', 'precision' => 2],
            ['code' => 'TOP', 'name' => 'Tongan Pa\'anga', 'symbol' => 'T$', 'precision' => 2],
            ['code' => 'WST', 'name' => 'Samoan Tala', 'symbol' => 'WS$', 'precision' => 2],
            ['code' => 'VUV', 'name' => 'Vanuatu Vatu', 'symbol' => 'VT', 'precision' => 0],
            ['code' => 'MUR', 'name' => 'Mauritian Rupee', 'symbol' => 'Rs', 'precision' => 2],
            ['code' => 'MVR', 'name' => 'Maldivian Rufiyaa', 'symbol' => 'Rf', 'precision' => 2],
            ['code' => 'SCR', 'name' => 'Seychellois Rupee', 'symbol' => 'SR', 'precision' => 2],
            ['code' => 'ETB', 'name' => 'Ethiopian Birr', 'symbol' => 'Br', 'precision' => 2],
            ['code' => 'TZS', 'name' => 'Tanzanian Shilling', 'symbol' => 'TSh', 'precision' => 2],
            ['code' => 'UGX', 'name' => 'Ugandan Shilling', 'symbol' => 'USh', 'precision' => 0],
            ['code' => 'RWF', 'name' => 'Rwandan Franc', 'symbol' => 'RF', 'precision' => 0],
            ['code' => 'BIF', 'name' => 'Burundian Franc', 'symbol' => 'FBu', 'precision' => 0],
            ['code' => 'XOF', 'name' => 'West African CFA Franc', 'symbol' => 'CFA', 'precision' => 0],
            ['code' => 'XAF', 'name' => 'Central African CFA Franc', 'symbol' => 'FCFA', 'precision' => 0],
            ['code' => 'CDF', 'name' => 'Congolese Franc', 'symbol' => 'FC', 'precision' => 2],
            ['code' => 'AOA', 'name' => 'Angolan Kwanza', 'symbol' => 'Kz', 'precision' => 2],
            ['code' => 'ZMW', 'name' => 'Zambian Kwacha', 'symbol' => 'ZK', 'precision' => 2],
            ['code' => 'MWK', 'name' => 'Malawian Kwacha', 'symbol' => 'MK', 'precision' => 2],
            ['code' => 'MZN', 'name' => 'Mozambican Metical', 'symbol' => 'MT', 'precision' => 2],
            ['code' => 'BWP', 'name' => 'Botswana Pula', 'symbol' => 'P', 'precision' => 2],
            ['code' => 'NAD', 'name' => 'Namibian Dollar', 'symbol' => 'N$', 'precision' => 2],
            ['code' => 'SZL', 'name' => 'Swazi Lilangeni', 'symbol' => 'E', 'precision' => 2],
            ['code' => 'LSL', 'name' => 'Lesotho Loti', 'symbol' => 'L', 'precision' => 2],
            ['code' => 'MGA', 'name' => 'Malagasy Ariary', 'symbol' => 'Ar', 'precision' => 1],
            ['code' => 'SOS', 'name' => 'Somali Shilling', 'symbol' => 'Sh.So.', 'precision' => 2],
            ['code' => 'DJF', 'name' => 'Djiboutian Franc', 'symbol' => 'Fdj', 'precision' => 0],
            ['code' => 'ERN', 'name' => 'Eritrean Nakfa', 'symbol' => 'Nfk', 'precision' => 2],
            ['code' => 'SDG', 'name' => 'Sudanese Pound', 'symbol' => 'ج.س.', 'precision' => 2],
            ['code' => 'SSP', 'name' => 'South Sudanese Pound', 'symbol' => 'SS£', 'precision' => 2],
            ['code' => 'LYD', 'name' => 'Libyan Dinar', 'symbol' => 'LD', 'precision' => 3],
            ['code' => 'MRU', 'name' => 'Mauritanian Ouguiya', 'symbol' => 'UM', 'precision' => 2],
            ['code' => 'GMD', 'name' => 'Gambian Dalasi', 'symbol' => 'D', 'precision' => 2],
            ['code' => 'CVE', 'name' => 'Cape Verdean Escudo', 'symbol' => 'Esc', 'precision' => 2],
            ['code' => 'STN', 'name' => 'Sao Tome & Principe Dobra', 'symbol' => 'Db', 'precision' => 2],
            ['code' => 'SLL', 'name' => 'Sierra Leonean Leone', 'symbol' => 'Le', 'precision' => 2],
            ['code' => 'LRD', 'name' => 'Liberian Dollar', 'symbol' => 'L$', 'precision' => 2],
            ['code' => 'GNF', 'name' => 'Guinean Franc', 'symbol' => 'FG', 'precision' => 0],
            ['code' => 'SYP', 'name' => 'Syrian Pound', 'symbol' => '£S', 'precision' => 2],
            ['code' => 'LBP', 'name' => 'Lebanese Pound', 'symbol' => 'ل.ل', 'precision' => 2],
            ['code' => 'IQD', 'name' => 'Iraqi Dinar', 'symbol' => 'ع.د', 'precision' => 3],
            ['code' => 'IRR', 'name' => 'Iranian Rial', 'symbol' => '﷼', 'precision' => 2],
            ['code' => 'AFN', 'name' => 'Afghan Afghani', 'symbol' => '؋', 'precision' => 2],
            ['code' => 'YER', 'name' => 'Yemeni Rial', 'symbol' => '﷼', 'precision' => 2],
            ['code' => 'KGS', 'name' => 'Kyrgyzstani Som', 'symbol' => 'с', 'precision' => 2],
            ['code' => 'TJS', 'name' => 'Tajikistani Somoni', 'symbol' => 'SM', 'precision' => 2],
            ['code' => 'TMT', 'name' => 'Turkmenistani Manat', 'symbol' => 'm', 'precision' => 2],
            ['code' => 'BND', 'name' => 'Brunei Dollar', 'symbol' => 'B$', 'precision' => 2],
            ['code' => 'KPW', 'name' => 'North Korean Won', 'symbol' => '₩', 'precision' => 2],
            ['code' => 'MOP', 'name' => 'Macanese Pataca', 'symbol' => 'MOP$', 'precision' => 2],
            ['code' => 'BZD', 'name' => 'Belize Dollar', 'symbol' => 'BZ$', 'precision' => 2],
            ['code' => 'GYD', 'name' => 'Guyanese Dollar', 'symbol' => 'GY$', 'precision' => 2],
            ['code' => 'SRD', 'name' => 'Surinamese Dollar', 'symbol' => 'SR$', 'precision' => 2],
            ['code' => 'HTG', 'name' => 'Haitian Gourde', 'symbol' => 'G', 'precision' => 2],
            ['code' => 'CUP', 'name' => 'Cuban Peso', 'symbol' => 'CUP$', 'precision' => 2],
            ['code' => 'CUC', 'name' => 'Cuban Convertible Peso', 'symbol' => 'CUC$', 'precision' => 2],
            ['code' => 'FKP', 'name' => 'Falkland Islands Pound', 'symbol' => 'FK£', 'precision' => 2],
            ['code' => 'GIP', 'name' => 'Gibraltar Pound', 'symbol' => '£', 'precision' => 2],
            ['code' => 'SHP', 'name' => 'Saint Helena Pound', 'symbol' => '£', 'precision' => 2],
            ['code' => 'GGP', 'name' => 'Guernsey Pound', 'symbol' => '£', 'precision' => 2],
            ['code' => 'JEP', 'name' => 'Jersey Pound', 'symbol' => '£', 'precision' => 2],
            ['code' => 'IMP', 'name' => 'Isle of Man Pound', 'symbol' => '£', 'precision' => 2],
            ['code' => 'BTC', 'name' => 'Bitcoin', 'symbol' => '₿', 'precision' => 8],
            ['code' => 'ETH', 'name' => 'Ethereum', 'symbol' => 'Ξ', 'precision' => 18],
            ['code' => 'USDT', 'name' => 'Tether', 'symbol' => '₮', 'precision' => 6],
            ['code' => 'XAU', 'name' => 'Gold (Troy Ounce)', 'symbol' => 'XAU', 'precision' => 4],
            ['code' => 'XAG', 'name' => 'Silver (Troy Ounce)', 'symbol' => 'XAG', 'precision' => 4],
        ];
    }
}
